### ISSUE TITLE
Notify caller about which command has failed

### ISSUE THREAD

**Issue by kevgo** [allonsy/currant#7]
Currant returns a `Vec<ExitStatus>` for commands it runs. It would be nice to get richer information:

- the `name` of the command run (as given to `ConsoleCommand::from_string`)
- the actual shell command run
- the `ExitStatus`

This is helpful for example when running a number of commands concurrently and one of them fails. The caller might want to know which exact command has failed.

**Comment by allonsy** [comment]
_technically_ the order of commands is preserved here (so the nth exit status is the nth command's status). But I'll add the `name` provided for clarity.

I hesitate to add the shell command run because if the user provides the command via argv, unparsing can be a little tricky (do we add quotes if needed?). 
I'd rather provide the name back and let the caller match it to the command provided.

**Comment by allonsy** [comment]
I can provide the name of the executable run but I'm not sure that is much better than the `name`.
The `name` var is supposed to be the "human-readable" element to the command so it makes sense that it is returned.

**Comment by kevgo** [comment]
#9 contains an idea on how to return the full command string that was running.
